all:
  children:
    minecraft_servers:
      hosts:
        minecraft:
          ansible_host: "{{ lookup('env', 'MINECRAFT_SERVER_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
