all:
  children:
    minecraft_servers:
      hosts:
        minecraft:
          ansible_host: "{{ lookup('env', 'MINECRAFT_SERVER_IP') }}"
          ansible_user: ec2-user
          ansible_ssh_private_key_file: "../terraform/minecraft-server-ssh.pem"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
