---
- name: Configure Minecraft Server
  hosts: minecraft_servers
  become: yes
  vars:
    minecraft_version: "1.20.4"
    minecraft_dir: "/opt/minecraft"
    minecraft_user: "minecraft"
    minecraft_group: "minecraft"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - openjdk-17-jre-headless
          - screen
          - wget
          - curl
        state: present

    - name: Create minecraft user
      user:
        name: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        shell: /bin/bash
        create_home: yes

    - name: Create minecraft directory
      file:
        path: "{{ minecraft_dir }}"
        state: directory
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0755"

    - name: Download Minecraft server
      get_url:
        url: "https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar"
        dest: "{{ minecraft_dir }}/server.jar"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"

    - name: Create eula.txt
      copy:
        content: "eula=true"
        dest: "{{ minecraft_dir }}/eula.txt"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"

    - name: Create server.properties
      template:
        src: server.properties.j2
        dest: "{{ minecraft_dir }}/server.properties"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"

    - name: Create systemd service file
      template:
        src: minecraft.service.j2
        dest: /etc/systemd/system/minecraft.service
        mode: "0644"

    - name: Start and enable Minecraft service
      systemd:
        name: minecraft
        state: started
        enabled: yes
        daemon_reload: yes
