---
- name: Configure Minecraft Server
  hosts: all
  become: yes
  vars:
    minecraft_version: "1.20.4"
    minecraft_dir: "/opt/minecraft"
    minecraft_user: "minecraft"
    minecraft_group: "minecraft"
    minecraft_server_url: "https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar"

  tasks:
    - name: Update dnf cache
      dnf:
        update_cache: yes

    - name: Install required packages
      dnf:
        name:
          - java-21-amazon-corretto-headless
          - screen
          - wget
          - curl-minimal
        state: present

    - name: Verify Java package installation
      shell: rpm -q java-21-amazon-corretto-headless
      register: java_package
      changed_when: false
      failed_when: java_package.rc != 0

    - name: Find Java executable using which
      shell: which java
      register: java_which
      changed_when: false
      failed_when: java_which.rc != 0

    - name: Set Java path from which
      set_fact:
        java_path: "{{ java_which.stdout }}"

    - name: Verify Java installation
      command: "{{ java_path }} -version"
      register: java_version
      changed_when: false

    - name: Create minecraft group
      group:
        name: "{{ minecraft_group }}"
        state: present

    - name: Create minecraft user
      user:
        name: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Create minecraft directory
      file:
        path: "{{ minecraft_dir }}"
        state: directory
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0755"

    - name: Download Minecraft server
      get_url:
        url: "{{ minecraft_server_url }}"
        dest: "{{ minecraft_dir }}/server.jar"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"

    - name: Create eula.txt
      copy:
        dest: "{{ minecraft_dir }}/eula.txt"
        content: "eula=true\n"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"

    - name: Create server.properties
      template:
        src: server.properties.j2
        dest: "{{ minecraft_dir }}/server.properties"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: "0644"

    - name: Create systemd service file
      template:
        src: minecraft.service.j2
        dest: /etc/systemd/system/minecraft.service
        owner: root
        group: root
        mode: "0644"
      notify:
        - Reload systemd

    - name: Start Minecraft service
      systemd:
        name: minecraft
        state: started
        daemon_reload: yes

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
